/**
 * Synthetic Demo Data — 25 fictional people for demonstration mode.
 * ⚠️ ALL DATA IS FICTIONAL. These are NOT real people.
 * Never mix synthetic data into real-person results.
 */

export interface SyntheticPerson {
  name: string
  linkedinUrl: string
  instagramUrl: string
  avatarSeed: string
  linkedinData: {
    name: string
    headline: string
    about: string
    skills: string[]
    source: string
  }
  instagramData: {
    username: string
    profileUrl: string
    displayName: string
    bio: string
    hashtags: string[]
    recentCaptions: string[]
    source: string
  }
}

export const SYNTHETIC_PEOPLE: SyntheticPerson[] = [
  {
    name: 'Maya Chen',
    linkedinUrl: 'https://www.linkedin.com/in/maya-chen-demo/',
    instagramUrl: 'https://www.instagram.com/maya.creates.demo/',
    avatarSeed: 'maya',
    linkedinData: {
      name: 'Maya Chen',
      headline: 'UX Designer at Figma | Design Systems Enthusiast',
      about: 'I craft intuitive digital experiences that bridge technology and human behavior. Passionate about accessibility and inclusive design. When not designing, you\'ll find me at ceramics class or hiking Bay Area trails.',
      skills: ['UX Design', 'Figma', 'Design Systems', 'User Research', 'Prototyping', 'Accessibility'],
      source: 'og_tags',
    },
    instagramData: {
      username: 'maya.creates.demo',
      profileUrl: 'https://www.instagram.com/maya.creates.demo/',
      displayName: 'Maya Chen',
      bio: '🎨 UX Designer by day, ceramics artist by weekend | Trail runner 🌲 | Bay Area based | Coffee snob ☕ #designthinking #ceramics #hiking',
      hashtags: ['#designthinking', '#ceramics', '#hiking', '#coffee', '#bayarea'],
      recentCaptions: [
        'New pottery piece! 3 hours of centering clay and I finally got it right. 🏺 There\'s something meditative about ceramics.',
        'Best morning run yet — 10 miles on the Marin Headlands trail. Views were unreal.',
        'Design critique day at work. Nothing sharpens your thinking like defending your choices.',
        'Weekend reading: "The Design of Everyday Things" for the third time. Still finding new insights.',
        'Coffee shop hopping in the Mission. Third stop of the day, still searching for the perfect flat white.',
      ],
      source: 'og_tags',
    },
  },
  {
    name: 'James Okonkwo',
    linkedinUrl: 'https://www.linkedin.com/in/james-okonkwo-demo/',
    instagramUrl: 'https://www.instagram.com/james.builds.demo/',
    avatarSeed: 'james',
    linkedinData: {
      name: 'James Okonkwo',
      headline: 'Software Engineer at Stripe | Open Source Contributor',
      about: 'Backend engineer specializing in distributed systems and payment infrastructure. I love solving hard problems at scale. Outside work: jazz musician, avid reader of African literature, and amateur chef.',
      skills: ['Python', 'Go', 'Distributed Systems', 'PostgreSQL', 'Kubernetes', 'API Design'],
      source: 'og_tags',
    },
    instagramData: {
      username: 'james.builds.demo',
      profileUrl: 'https://www.instagram.com/james.builds.demo/',
      displayName: 'James Okonkwo',
      bio: '💻 Engineer @Stripe | 🎷 Jazz musician | 📚 African lit enthusiast | Cooking my way through Lagos recipes | NYC 🗽 #jazz #coding #food',
      hashtags: ['#jazz', '#coding', '#food', '#africanlit', '#nyc'],
      recentCaptions: [
        'Open mic night at Smalls Jazz Club. Finally played my arrangement of Giant Steps. Miles still has me beat.',
        'Cooked jollof rice from my grandmother\'s recipe. The kitchen smelled like Lagos for an hour.',
        'Reading "Half of a Yellow Sun" for the second time. Chimamanda is incomparable.',
        'Shipped a new feature today — concurrent idempotency keys for payment retries. The edge cases were brutal.',
        'Weekend hackathon: built a Jazz chord progression generator in 8 hours. It\'s surprisingly musical.',
      ],
      source: 'og_tags',
    },
  },
  {
    name: 'Sofia Reyes',
    linkedinUrl: 'https://www.linkedin.com/in/sofia-reyes-demo/',
    instagramUrl: 'https://www.instagram.com/sofia.explores.demo/',
    avatarSeed: 'sofia',
    linkedinData: {
      name: 'Sofia Reyes',
      headline: 'Environmental Scientist | Climate Advocacy | Stanford PhD Candidate',
      about: 'Researching carbon capture mechanisms in coastal wetlands. Passionate about translating climate science into policy. Also a competitive rock climber and volunteer trail crew member.',
      skills: ['Climate Science', 'GIS Mapping', 'Python', 'R', 'Science Communication', 'Policy Analysis'],
      source: 'og_tags',
    },
    instagramData: {
      username: 'sofia.explores.demo',
      profileUrl: 'https://www.instagram.com/sofia.explores.demo/',
      displayName: 'Sofia Reyes',
      bio: '🌿 PhD Candidate @Stanford Climate | 🧗 Rock climber | 🌊 Wetlands researcher | Building a livable future one carbon molecule at a time #climateaction #rockclimbing',
      hashtags: ['#climateaction', '#rockclimbing', '#science', '#wetlands', '#stanford'],
      recentCaptions: [
        'Field day in the Elkhorn Slough — collected 40 sediment cores. My boots will never be the same.',
        'Sent my project route at the gym today! 5.12a felt impossible three months ago.',
        'Climate panel at the State Capitol tomorrow. Science-to-policy translation is where I feel most alive.',
        'Writing my third chapter and the data is finally telling a coherent story. Coffee consumption: astronomical.',
        'Volunteer trail work in Yosemite this weekend. 6 miles of drainage cleared.',
      ],
      source: 'og_tags',
    },
  },
  {
    name: 'Aiden Walsh',
    linkedinUrl: 'https://www.linkedin.com/in/aiden-walsh-demo/',
    instagramUrl: 'https://www.instagram.com/aiden.frames.demo/',
    avatarSeed: 'aiden',
    linkedinData: {
      name: 'Aiden Walsh',
      headline: 'Documentary Filmmaker & Photojournalist | National Geographic Contributor',
      about: 'I tell stories through images. Former photojournalist turned documentary filmmaker. My work focuses on underrepresented communities and environmental stories. Currently producing a doc about Greenland ice loss.',
      skills: ['Documentary Filmmaking', 'Photography', 'Storytelling', 'Adobe Premiere', 'DaVinci Resolve', 'Journalism'],
      source: 'og_tags',
    },
    instagramData: {
      username: 'aiden.frames.demo',
      profileUrl: 'https://www.instagram.com/aiden.frames.demo/',
      displayName: 'Aiden Walsh',
      bio: '📷 Documentary filmmaker | NatGeo contributor | 🧊 Currently filming in Greenland | Stories that matter | Dublin→NYC #documentary #photojournalism #climate',
      hashtags: ['#documentary', '#photojournalism', '#climate', '#greenland', '#storytelling'],
      recentCaptions: [
        'Day 12 on the ice sheet. The calving sounds are unlike anything I\'ve recorded before.',
        'Interview with the last sled dog musher in the region. His family has lived here for 8 generations.',
        'Got the shot I\'ve been waiting three weeks for — iceberg at golden hour. Worth every frozen finger.',
        'Back in NYC for post-production. The edit is going to be brutal in the best way.',
        'Teaching a photo workshop at the community center. Watching people see through a viewfinder for the first time.',
      ],
      source: 'og_tags',
    },
  },
  {
    name: 'Priya Sharma',
    linkedinUrl: 'https://www.linkedin.com/in/priya-sharma-demo/',
    instagramUrl: 'https://www.instagram.com/priya.codes.demo/',
    avatarSeed: 'priya',
    linkedinData: {
      name: 'Priya Sharma',
      headline: 'ML Engineer at DeepMind | NeurIPS Researcher | Kathak Dancer',
      about: 'Building the next generation of multimodal AI. Published at NeurIPS and ICLR. I believe AI should amplify human creativity, not replace it. Classical Kathak dancer for 18 years.',
      skills: ['Machine Learning', 'PyTorch', 'Computer Vision', 'Python', 'Research', 'CUDA'],
      source: 'og_tags',
    },
    instagramData: {
      username: 'priya.codes.demo',
      profileUrl: 'https://www.instagram.com/priya.codes.demo/',
      displayName: 'Priya Sharma',
      bio: '🤖 ML @DeepMind | 💃 Kathak dancer for 18 yrs | PhD in AI | Books + chai + rainy days | London 🇬🇧 #machinelearning #kathak #indiantechwoman',
      hashtags: ['#machinelearning', '#kathak', '#ai', '#indiantechwoman', '#london'],
      recentCaptions: [
        'Performed at the Royal Opera House last night. 300 people watching your footwork is a different kind of pressure than a paper deadline.',
        'Paper accepted at NeurIPS! 18 months of experiments finally paid off. The celebratory chai was earned.',
        'Training run crashed at hour 47. Saved checkpoints for the win. Never skip your checkpoints.',
        'Taught a Kathak masterclass this weekend. Seeing students understand the mathematics in rhythm is magical.',
        'Reading "Gödel, Escher, Bach" again. It gets stranger and more beautiful every time.',
      ],
      source: 'og_tags',
    },
  },
  {
    name: 'Marcus Johnson',
    linkedinUrl: 'https://www.linkedin.com/in/marcus-johnson-demo/',
    instagramUrl: 'https://www.instagram.com/marcus.runs.demo/',
    avatarSeed: 'marcus',
    linkedinData: {
      name: 'Marcus Johnson',
      headline: 'High School Track Coach & Physical Education Teacher | Boston Marathon Finisher',
      about: 'Teaching young athletes to find their limits and push past them. 12 years coaching. Boston Marathon finisher (4x). Former collegiate sprinter. Believe running teaches everything about life.',
      skills: ['Coaching', 'Athletic Training', 'Sports Psychology', 'Curriculum Development', 'Physical Education'],
      source: 'og_tags',
    },
    instagramData: {
      username: 'marcus.runs.demo',
      profileUrl: 'https://www.instagram.com/marcus.runs.demo/',
      displayName: 'Marcus Johnson',
      bio: '🏃‍♂️ Coach & teacher | 4x Boston Marathon finisher | Helping young athletes believe in themselves | 📚 Reading everything | Atlanta, GA #running #coaching #education',
      hashtags: ['#running', '#coaching', '#education', '#marathontraining', '#atlanta'],
      recentCaptions: [
        'My kids won the regional relay championship today. The look on their faces when they crossed the line.',
        'Boston training week 8: 80 miles. Legs are complaining but my mind is clear.',
        'Reading "Mindset" by Carol Dweck with my team. Every athlete should read this.',
        'Parent-teacher conferences done. The relationship between mental resilience in sport and academics is real.',
        'Early morning 20-miler on the Silver Comet Trail. The best thinking happens at mile 15.',
      ],
      source: 'og_tags',
    },
  },
  {
    name: 'Zoe Kim',
    linkedinUrl: 'https://www.linkedin.com/in/zoe-kim-demo/',
    instagramUrl: 'https://www.instagram.com/zoe.bakes.demo/',
    avatarSeed: 'zoe',
    linkedinData: {
      name: 'Zoe Kim',
      headline: 'Pastry Chef & Food Writer | James Beard Foundation Semifinalist',
      about: 'Executive pastry chef at Quince, San Francisco. James Beard semifinalist for Outstanding Pastry Chef. Writing my first cookbook. Dedicated to reimagining Korean flavors in French pastry.',
      skills: ['Pastry', 'Recipe Development', 'Food Writing', 'Kitchen Management', 'Menu Design'],
      source: 'og_tags',
    },
    instagramData: {
      username: 'zoe.bakes.demo',
      profileUrl: 'https://www.instagram.com/zoe.bakes.demo/',
      displayName: 'Zoe Kim',
      bio: '🥐 Pastry Chef @Quince SF | 📖 Cookbook in progress | Korean-French fusion | James Beard semifinalist | SF → Seoul #pastry #foodwriter #koreancooking',
      hashtags: ['#pastry', '#foodwriter', '#koreancooking', '#jamesbeard', '#chefsofinstagram'],
      recentCaptions: [
        'New tasting menu dessert: black sesame opera cake with yuzu cremeux. It took 12 iterations.',
        'Cookbook research trip to Seoul — eating my way through Gwangjang Market.',
        'Prep starts at 5am. The kitchen belongs to a different kind of person at that hour.',
        'Teaching a croissant lamination workshop this weekend. Butter, patience, and 72 hours of cold.',
        'Reading old Escoffier while developing new recipes. The classics exist for a reason.',
      ],
      source: 'og_tags',
    },
  },
  {
    name: 'Luca Ricci',
    linkedinUrl: 'https://www.linkedin.com/in/luca-ricci-demo/',
    instagramUrl: 'https://www.instagram.com/luca.builds.demo/',
    avatarSeed: 'luca',
    linkedinData: {
      name: 'Luca Ricci',
      headline: 'Architect & Urban Designer | Sustainable Cities | Rome → NYC',
      about: 'Designing cities for people, not cars. Passionate about adaptive reuse and sustainable urban design. Projects in 12 countries. Teaching at Columbia GSAPP on urban futures.',
      skills: ['Architecture', 'Urban Design', 'Rhino', 'AutoCAD', 'Sustainability', 'Teaching'],
      source: 'og_tags',
    },
    instagramData: {
      username: 'luca.builds.demo',
      profileUrl: 'https://www.instagram.com/luca.builds.demo/',
      displayName: 'Luca Ricci',
      bio: '🏛️ Architect | Urban futures @ColumbiGSAPP | Adaptive reuse obsessive | 🚲 Cyclist | Espresso supremacist | Rome→NYC #architecture #urbandesign #cycling',
      hashtags: ['#architecture', '#urbandesign', '#cycling', '#adaptivereuse', '#sustainablecities'],
      recentCaptions: [
        'Bike commute data from a year of NYC cycling. The infrastructure gaps are telling a design story.',
        'Final review at Columbia — my students are designing better cities than I was at their age.',
        'Rome trip for a project site visit. Every cobblestone is a design lesson.',
        'The Highline at golden hour. Adaptive reuse doesn\'t get better than this.',
        'Reading "The Death and Life of Great American Cities" with my studio class. Jane Jacobs is timeless.',
      ],
      source: 'og_tags',
    },
  },
  {
    name: 'Amara Diallo',
    linkedinUrl: 'https://www.linkedin.com/in/amara-diallo-demo/',
    instagramUrl: 'https://www.instagram.com/amara.writes.demo/',
    avatarSeed: 'amara',
    linkedinData: {
      name: 'Amara Diallo',
      headline: 'Author & Creative Writing Professor | Penguin Random House | PEN Award Winner',
      about: 'Literary fiction author. Third novel forthcoming from Penguin Random House. PEN/Robert W. Bingham Prize winner. Teaching creative writing at NYU. Born in Dakar, writes about diaspora identity.',
      skills: ['Creative Writing', 'Literary Fiction', 'Teaching', 'Editing', 'Public Speaking'],
      source: 'og_tags',
    },
    instagramData: {
      username: 'amara.writes.demo',
      profileUrl: 'https://www.instagram.com/amara.writes.demo/',
      displayName: 'Amara Diallo',
      bio: '✍️ Author | @Penguin | Professor @NYU | PEN Award winner | 📖 Third novel coming 2025 | Dakar→NYC | Telling African diaspora stories #literaryfiction #diaspora #writing',
      hashtags: ['#literaryfiction', '#diaspora', '#writing', '#africanwriter', '#nyu'],
      recentCaptions: [
        'Manuscript delivered. Three years of my life, now someone else\'s problem to edit.',
        'Workshop today: helping students find the authentic voice underneath the performative one.',
        'Reading at the Brooklyn Book Festival. The room was full. Words still move people.',
        'Research trip to Dakar for novel 4. Memory and imagination competing.',
        'Office hours always run over. These students have real things to say.',
      ],
      source: 'og_tags',
    },
  },
  {
    name: 'Ethan Park',
    linkedinUrl: 'https://www.linkedin.com/in/ethan-park-demo/',
    instagramUrl: 'https://www.instagram.com/ethan.invests.demo/',
    avatarSeed: 'ethan',
    linkedinData: {
      name: 'Ethan Park',
      headline: 'VC Investor at Sequoia | Climate Tech Focus | Former Founder',
      about: 'Investing in climate tech companies at Sequoia Capital. Previously founded a clean energy startup (acquired 2022). Stanford MBA. Believe technology is our best shot at fixing what we broke.',
      skills: ['Venture Capital', 'Climate Tech', 'Startups', 'Financial Modeling', 'Due Diligence', 'Strategy'],
      source: 'og_tags',
    },
    instagramData: {
      username: 'ethan.invests.demo',
      profileUrl: 'https://www.instagram.com/ethan.invests.demo/',
      displayName: 'Ethan Park',
      bio: '💰 VC @Sequoia | 🌱 Climate tech | Former founder | 🎾 Tennis | ♟️ Chess | Building the climate future | SF #climatetech #venturecapital #tennis',
      hashtags: ['#climatetech', '#venturecapital', '#tennis', '#chess', '#startups'],
      recentCaptions: [
        'Portfolio company just closed a $50M Series B. Proud doesn\'t cover it.',
        'Tennis match at 6am is the only acceptable way to start a Monday.',
        'Climate Tech Summit today — the quality of founders is unlike anything I\'ve seen.',
        'Chess tournament, came third. My endgame needs work.',
        'Reading annual reports all weekend. Due diligence is the unglamorous part nobody talks about.',
      ],
      source: 'og_tags',
    },
  },
  {
    name: 'Nina Hoffman',
    linkedinUrl: 'https://www.linkedin.com/in/nina-hoffman-demo/',
    instagramUrl: 'https://www.instagram.com/nina.heals.demo/',
    avatarSeed: 'nina',
    linkedinData: {
      name: 'Nina Hoffman',
      headline: 'Emergency Medicine Physician | Global Health | Volunteer with MSF',
      about: 'ER doctor with a passion for global health equity. Three MSF deployments to South Sudan and DRC. Teaching medical students how to stay human under pressure. Yoga instructor on the side.',
      skills: ['Emergency Medicine', 'Trauma Care', 'Global Health', 'Medical Education', 'Team Leadership'],
      source: 'og_tags',
    },
    instagramData: {
      username: 'nina.heals.demo',
      profileUrl: 'https://www.instagram.com/nina.heals.demo/',
      displayName: 'Nina Hoffman',
      bio: '🏥 ER Doctor | 🌍 @MSF volunteer | Global health equity | Yoga 🧘‍♀️ | Finding stillness in the chaos | Chicago #emergencymedicine #globalhealth #yoga',
      hashtags: ['#emergencymedicine', '#globalhealth', '#yoga', '#msf', '#medtwitter'],
      recentCaptions: [
        'Back from South Sudan. Words don\'t capture it. Thank you to the team.',
        'Sunday morning yoga — the medicine I prescribe most and practice least. Not today.',
        'Trauma simulation training with med students. The quieter they get, the harder they\'re thinking.',
        'Global Health conference paper accepted. This one is for the field workers who collected the data.',
        'Long shift. The ER at 3am is its own universe.',
      ],
      source: 'og_tags',
    },
  },
  {
    name: 'Omar Hassan',
    linkedinUrl: 'https://www.linkedin.com/in/omar-hassan-demo/',
    instagramUrl: 'https://www.instagram.com/omar.sounds.demo/',
    avatarSeed: 'omar',
    linkedinData: {
      name: 'Omar Hassan',
      headline: 'Music Producer & Audio Engineer | Grammy Nominated | Cairo → LA',
      about: 'Grammy-nominated producer working across hip-hop, R&B, and electronic music. Produced tracks for artists with 2B+ streams. Blending traditional Egyptian music with contemporary production.',
      skills: ['Music Production', 'Audio Engineering', 'Ableton Live', 'Sound Design', 'Mixing', 'Mastering'],
      source: 'og_tags',
    },
    instagramData: {
      username: 'omar.sounds.demo',
      profileUrl: 'https://www.instagram.com/omar.sounds.demo/',
      displayName: 'Omar Hassan',
      bio: '🎛️ Music producer | Grammy nominated | Cairo→LA | Blending East and West, one beat at a time 🎵 | 2B+ streams | Studio forever #musicproducer #hiphop #egyptianmusic',
      hashtags: ['#musicproducer', '#hiphop', '#egyptianmusic', '#grammynominated', '#audioengineering'],
      recentCaptions: [
        'Finished the beat tape at 4am. Sleep is overrated. Art is not.',
        'Cairo for a week — recording traditional oud sessions. The samples are otherworldly.',
        'Mixing session with one of my favorite vocalists. The chemistry when it clicks.',
        'Studio has been home for 11 days straight. But we\'ve got something special.',
        'Teaching production to kids from South Central. They hear things I don\'t.',
      ],
      source: 'og_tags',
    },
  },
  {
    name: 'Isabella Torres',
    linkedinUrl: 'https://www.linkedin.com/in/isabella-torres-demo/',
    instagramUrl: 'https://www.instagram.com/isabella.codes.demo/',
    avatarSeed: 'isabella',
    linkedinData: {
      name: 'Isabella Torres',
      headline: 'Data Journalist | NY Times | Telling stories through data visualization',
      about: 'Data journalist at The New York Times. Translating complex data into visual stories that anyone can understand. Harvard statistics + Columbia journalism. Advocate for data literacy.',
      skills: ['Data Journalism', 'D3.js', 'R', 'Python', 'Data Visualization', 'Investigative Reporting'],
      source: 'og_tags',
    },
    instagramData: {
      username: 'isabella.codes.demo',
      profileUrl: 'https://www.instagram.com/isabella.codes.demo/',
      displayName: 'Isabella Torres',
      bio: '📊 Data journalist @NYT | Harvard stats + Columbia journalism | Charts that change minds | Salsa dancer 💃 | NYC #datajournalism #datavis #journalism',
      hashtags: ['#datajournalism', '#datavis', '#journalism', '#salsa', '#nyc'],
      recentCaptions: [
        'Six-month investigation published today. The data was hiding a story nobody wanted to tell.',
        'Salsa class Thursday night. The only time my brain completely turns off.',
        'D3.js is poetry when you get it right. An interactive explainer for 3M readers.',
        'Teaching data literacy in the newsroom. Not everyone loves the spreadsheets yet.',
        'Read 3 issues of The Pudding this weekend. Visual journalism at its finest.',
      ],
      source: 'og_tags',
    },
  },
  {
    name: 'Ryan O\'Brien',
    linkedinUrl: 'https://www.linkedin.com/in/ryan-obrien-demo/',
    instagramUrl: 'https://www.instagram.com/ryan.surfs.demo/',
    avatarSeed: 'ryan',
    linkedinData: {
      name: "Ryan O'Brien",
      headline: 'Marine Biologist & Science Educator | NOAA Research Associate',
      about: 'Studying coral reef resilience at NOAA. Science communicator — making ocean science accessible to everyone. Competitive surfer. Running ocean literacy programs in underserved coastal communities.',
      skills: ['Marine Biology', 'Scientific Research', 'Science Communication', 'SCUBA', 'Data Analysis', 'Education'],
      source: 'og_tags',
    },
    instagramData: {
      username: 'ryan.surfs.demo',
      profileUrl: 'https://www.instagram.com/ryan.surfs.demo/',
      displayName: "Ryan O'Brien",
      bio: '🌊 Marine biologist @NOAA | 🏄 Surfer | Coral reef guardian | Science for everyone | Maui, HI #marinebiology #surfing #coralreefs #scicomm',
      hashtags: ['#marinebiology', '#surfing', '#coralreefs', '#scicomm', '#oceanconservation'],
      recentCaptions: [
        'Dive survey today — found a recovering coral patch we\'d written off three years ago. Never stop watching.',
        'Dawn patrol in 8-foot surf. The ocean doesn\'t care about your schedule.',
        'Ocean literacy program with 60 kids from Kailua. The first time they held a starfish.',
        'Paper on thermally tolerant coral strains published in Nature Climate Change.',
        'SCUBA certification class this weekend. Giving people access to a world they didn\'t know existed.',
      ],
      source: 'og_tags',
    },
  },
  {
    name: 'Jasmine Lee',
    linkedinUrl: 'https://www.linkedin.com/in/jasmine-lee-demo/',
    instagramUrl: 'https://www.instagram.com/jasmine.moves.demo/',
    avatarSeed: 'jasmine',
    linkedinData: {
      name: 'Jasmine Lee',
      headline: 'Choreographer & Artistic Director | Broadway & Contemporary Dance',
      about: 'Tony-nominated choreographer. Artistic director of Kinetic Arts Company. Blending hip-hop, contemporary, and Korean traditional dance forms. Creating work that is as much about politics as it is about movement.',
      skills: ['Choreography', 'Dance Direction', 'Arts Administration', 'Movement Analysis', 'Collaboration'],
      source: 'og_tags',
    },
    instagramData: {
      username: 'jasmine.moves.demo',
      profileUrl: 'https://www.instagram.com/jasmine.moves.demo/',
      displayName: 'Jasmine Lee',
      bio: '💃 Choreographer | Tony nominated | Artistic Director @KineticArts | Movement is political | NYC #choreography #broadway #contemporarydance #koreandance',
      hashtags: ['#choreography', '#broadway', '#contemporarydance', '#koreandance', '#dance'],
      recentCaptions: [
        'Opening night. Everything we\'ve worked toward for 18 months. The dancers were extraordinary.',
        'Rehearsal day 60. The piece is finally breathing on its own.',
        'Masterclass at Alvin Ailey today — 120 dancers who will move the world.',
        'Korea trip researching traditional Salpuri for the new piece. The grief in this dance is ancient.',
        'Wrote my director\'s note at 2am. The show opens in 11 days.',
      ],
      source: 'og_tags',
    },
  },
  {
    name: 'David Nguyen',
    linkedinUrl: 'https://www.linkedin.com/in/david-nguyen-demo/',
    instagramUrl: 'https://www.instagram.com/david.climbs.demo/',
    avatarSeed: 'david',
    linkedinData: {
      name: 'David Nguyen',
      headline: 'Startup Founder & CEO | Mental Health Tech | YC W23',
      about: 'Building technology to make mental health support accessible. YCombinator alum. First-gen Vietnamese American. Openly living with anxiety disorder — destigmatizing mental health in the tech industry.',
      skills: ['Entrepreneurship', 'Mental Health', 'Product Strategy', 'Fundraising', 'Team Building', 'React Native'],
      source: 'og_tags',
    },
    instagramData: {
      username: 'david.climbs.demo',
      profileUrl: 'https://www.instagram.com/david.climbs.demo/',
      displayName: 'David Nguyen',
      bio: '🧗 Rock climber | 🏢 CEO @MindBridge | YC W23 | Mental health advocate | First-gen | Vietnam→San Jose→SF #mentalhealth #climbing #startup #yc',
      hashtags: ['#mentalhealth', '#climbing', '#startup', '#yc', '#firstgenfounder'],
      recentCaptions: [
        'Climbed El Cap for the first time. 31 hours on the wall. I cried at the top.',
        'Talked about my anxiety disorder at a conference of 500 people. The DMs afterward showed why it matters.',
        'Closed our Series A. The team who believed in this mission before we had traction.',
        'Mental health day — actually taking one for the first time in a year. The gym, then nothing.',
        'Reading "Lost Connections" by Johann Hari. Everyone building in mental health should read this.',
      ],
      source: 'og_tags',
    },
  },
  {
    name: 'Fatima Al-Rashid',
    linkedinUrl: 'https://www.linkedin.com/in/fatima-alrashid-demo/',
    instagramUrl: 'https://www.instagram.com/fatima.leads.demo/',
    avatarSeed: 'fatima',
    linkedinData: {
      name: 'Fatima Al-Rashid',
      headline: 'International Human Rights Lawyer | UNHCR Special Advisor | Oxford LLM',
      about: 'Human rights lawyer working on refugee and asylum law. Special advisor to UNHCR. Oxford and Georgetown Law graduate. Advocate for dignified migration pathways. Speaking truth to power, one case at a time.',
      skills: ['Human Rights Law', 'International Law', 'Advocacy', 'Public Speaking', 'Legal Research', 'Diplomacy'],
      source: 'og_tags',
    },
    instagramData: {
      username: 'fatima.leads.demo',
      profileUrl: 'https://www.instagram.com/fatima.leads.demo/',
      displayName: 'Fatima Al-Rashid',
      bio: '⚖️ Human rights lawyer | @UNHCR Advisor | Refugee law | Oxford + Georgetown | Oud player 🎵 | Geneva→NYC #humanrights #refugeelaw #internationallaw',
      hashtags: ['#humanrights', '#refugeelaw', '#internationallaw', '#oud', '#advocate'],
      recentCaptions: [
        'Presented the refugee compact to the UN General Assembly. Eighteen months of work. The fight continues.',
        'Late-night oud practice. The music my grandmother taught me, in a city she never saw.',
        'Legal aid clinic this weekend — 40 asylum seekers in 8 hours. Exhausted and grateful.',
        'Oxford alumni panel on international law. The students ask better questions every year.',
        'New paper: "Procedural Justice in Refugee Determination." The system can be better.',
      ],
      source: 'og_tags',
    },
  },
  {
    name: 'Carlos Mendoza',
    linkedinUrl: 'https://www.linkedin.com/in/carlos-mendoza-demo/',
    instagramUrl: 'https://www.instagram.com/carlos.cooks.demo/',
    avatarSeed: 'carlos',
    linkedinData: {
      name: 'Carlos Mendoza',
      headline: 'Executive Chef & Restaurateur | James Beard Award Winner | CDMX → Chicago',
      about: 'James Beard Award-winning chef. Owner of three restaurants in Chicago celebrating Mexican regional cuisine. Cooking is cultural preservation. Working with indigenous communities to source and document ancestral ingredients.',
      skills: ['Culinary Arts', 'Menu Development', 'Restaurant Management', 'Cultural Preservation', 'Team Leadership'],
      source: 'og_tags',
    },
    instagramData: {
      username: 'carlos.cooks.demo',
      profileUrl: 'https://www.instagram.com/carlos.cooks.demo/',
      displayName: 'Carlos Mendoza',
      bio: '🌮 James Beard chef | 3 restaurants in Chicago | Mexican regional cuisine | Cultural preservation through food | CDMX born 🇲🇽 #mexicancuisine #chef #jamesbeard',
      hashtags: ['#mexicancuisine', '#chef', '#jamesbeard', '#culturalpreservation', '#chicago'],
      recentCaptions: [
        'Oaxacan chili sourcing trip. Three days in the mountains with producers who know flavors I\'ve never imagined.',
        'New tasting menu launches Friday. Seven courses, each one a different Mexican state.',
        'Cooking class for the community. Teaching abuelita recipes to their grandchildren.',
        'James Beard dinner in NYC. Cooking alongside legends.',
        'Farmers market at 5am. The best ingredients don\'t wait.',
      ],
      source: 'og_tags',
    },
  },
  {
    name: 'Hannah Goldstein',
    linkedinUrl: 'https://www.linkedin.com/in/hannah-goldstein-demo/',
    instagramUrl: 'https://www.instagram.com/hannah.designs.demo/',
    avatarSeed: 'hannah',
    linkedinData: {
      name: 'Hannah Goldstein',
      headline: 'Fashion Designer | Sustainable Textiles | RISD Graduate',
      about: 'Sustainable fashion designer. Designing collections using only deadstock and recycled materials. RISD trained. Believe fast fashion is an ethical failure. Exhibited at New York Fashion Week.',
      skills: ['Fashion Design', 'Textile Development', 'Pattern Making', 'Sustainable Design', 'Brand Strategy'],
      source: 'og_tags',
    },
    instagramData: {
      username: 'hannah.designs.demo',
      profileUrl: 'https://www.instagram.com/hannah.designs.demo/',
      displayName: 'Hannah Goldstein',
      bio: '👗 Sustainable fashion designer | RISD | NYFW | No new fabric, only rescued textiles | Vintage obsessive | BK #sustainablefashion #slowfashion #fashiondesigner',
      hashtags: ['#sustainablefashion', '#slowfashion', '#fashiondesigner', '#risd', '#nyfw'],
      recentCaptions: [
        'NYFW show complete. Every piece made from deadstock or reclaimed fabric. Zero waste.',
        'Vintage market haul: 30 lbs of fabric that will become something new.',
        'Pattern-making at midnight. The problem finally solved itself.',
        'Documentary night: "The True Cost." Watch it. Then buy less.',
        'Textile industry trip to Portugal — meeting the last mills doing things the right way.',
      ],
      source: 'og_tags',
    },
  },
  {
    name: 'Kenji Tanaka',
    linkedinUrl: 'https://www.linkedin.com/in/kenji-tanaka-demo/',
    instagramUrl: 'https://www.instagram.com/kenji.gardens.demo/',
    avatarSeed: 'kenji',
    linkedinData: {
      name: 'Kenji Tanaka',
      headline: 'Landscape Architect | Therapeutic Garden Design | Kyoto Institute of Design',
      about: 'Designing healing gardens for hospitals and mental health facilities. Research shows nature reduces recovery time and improves mental health outcomes. Kyoto-trained, now based in Portland.',
      skills: ['Landscape Architecture', 'Therapeutic Design', 'Horticulture', 'AutoCAD', 'Environmental Psychology'],
      source: 'og_tags',
    },
    instagramData: {
      username: 'kenji.gardens.demo',
      profileUrl: 'https://www.instagram.com/kenji.gardens.demo/',
      displayName: 'Kenji Tanaka',
      bio: '🌿 Landscape architect | Therapeutic gardens | Healing through nature | Kyoto→Portland | Ikebana 🌸 | Minimalist everything #landscape #therapeuticdesign #japanesedesign',
      hashtags: ['#landscape', '#therapeuticdesign', '#japanesedesign', '#ikebana', '#healing'],
      recentCaptions: [
        'Hospital rooftop garden installed. Patients can now see green from their rooms.',
        'Ikebana exhibition — arranging 40 stems into a meditation on impermanence.',
        'Portland rain is perfect for thinking. New project sketches.',
        'Research showing our hospital garden reduced patient anxiety scores by 34%.',
        'Morning walk through Japanese Garden. Studied the moss. Studied the silence.',
      ],
      source: 'og_tags',
    },
  },
  {
    name: 'Anya Petrov',
    linkedinUrl: 'https://www.linkedin.com/in/anya-petrov-demo/',
    instagramUrl: 'https://www.instagram.com/anya.skates.demo/',
    avatarSeed: 'anya',
    linkedinData: {
      name: 'Anya Petrov',
      headline: 'Aerospace Engineer at SpaceX | Propulsion Systems | Former Olympic Figure Skater',
      about: 'Rocket propulsion engineer by day, retired Olympian by background. Competed in figure skating for Russia at age 19 (Sochi 2014). Now engineering the next generation of reusable rocket engines.',
      skills: ['Aerospace Engineering', 'Propulsion Systems', 'MATLAB', 'Thermodynamics', 'CAD', 'Systems Engineering'],
      source: 'og_tags',
    },
    instagramData: {
      username: 'anya.skates.demo',
      profileUrl: 'https://www.instagram.com/anya.skates.demo/',
      displayName: 'Anya Petrov',
      bio: '🚀 Rocket engineer @SpaceX | ⛸️ Former Olympian (Sochi 2014) | Ice still calls me back | Moscow→LA | Precision in everything #aerospace #figureskating #spacex',
      hashtags: ['#aerospace', '#figureskating', '#spacex', '#rockets', '#olympian'],
      recentCaptions: [
        'Engine test fire. The sound of controlled chaos.',
        'Ice rink on Saturday morning. Old habits die hard, and I\'m glad they do.',
        'Mentoring women in engineering at USC. They have more fire than I did at their age.',
        'Watching the Starship launch from the pad. Still can\'t believe this is my job.',
        'Reading Feynman\'s lectures again. The joy of finding things out.',
      ],
      source: 'og_tags',
    },
  },
  {
    name: 'Benjamin Clark',
    linkedinUrl: 'https://www.linkedin.com/in/benjamin-clark-demo/',
    instagramUrl: 'https://www.instagram.com/ben.makes.demo/',
    avatarSeed: 'benjamin',
    linkedinData: {
      name: 'Benjamin Clark',
      headline: 'Product Manager at Notion | Second-time Founder | Book Club Curator',
      about: 'PM at Notion working on collaborative features. Previously founded an ed-tech startup (2019-2022). Curate a 200-person book club in San Francisco. Obsessed with how knowledge compounds.',
      skills: ['Product Management', 'User Research', 'Roadmapping', 'Data Analysis', 'Community Building'],
      source: 'og_tags',
    },
    instagramData: {
      username: 'ben.makes.demo',
      profileUrl: 'https://www.instagram.com/ben.makes.demo/',
      displayName: 'Benjamin Clark',
      bio: '📚 PM @Notion | Book club curator (200 members!) | Failed founder once, trying again | 🎸 Guitarist | SF #productmanagement #books #startup #bookclub',
      hashtags: ['#productmanagement', '#books', '#startup', '#bookclub', '#sf'],
      recentCaptions: [
        'Book club meeting 87. We read "The Dawn of Everything" — the conversation lasted 4 hours.',
        'Late-night guitar session. Learned a whole Elliott Smith song. Worth the calloused fingers.',
        'Sprint retrospective done — the team is shipping faster than ever and actually happier.',
        'Started a second book club focused only on first-generation immigrants who became founders.',
        'Rejected by three investors this week. The notes were useful. The sting was real.',
      ],
      source: 'og_tags',
    },
  },
  {
    name: 'Leila Ahmadi',
    linkedinUrl: 'https://www.linkedin.com/in/leila-ahmadi-demo/',
    instagramUrl: 'https://www.instagram.com/leila.creates.demo/',
    avatarSeed: 'leila',
    linkedinData: {
      name: 'Leila Ahmadi',
      headline: 'Visual Artist & Art Therapist | Tehran → Berlin | Trauma-Informed Creative Practice',
      about: 'Visual artist working at the intersection of art and healing. Licensed art therapist working with refugee communities. Work exhibited in Berlin, London, and Tehran. Artist-in-residence at Goldsmiths.',
      skills: ['Visual Art', 'Art Therapy', 'Community Practice', 'Exhibition Curation', 'Mixed Media'],
      source: 'og_tags',
    },
    instagramData: {
      username: 'leila.creates.demo',
      profileUrl: 'https://www.instagram.com/leila.creates.demo/',
      displayName: 'Leila Ahmadi',
      bio: '🎨 Artist + Art Therapist | @Goldsmiths Resident | Healing through making | Tehran→Berlin | Community art | Multilingual 🌍 #arttherapy #visualart #traumainformed',
      hashtags: ['#arttherapy', '#visualart', '#traumainformed', '#community', '#berlin'],
      recentCaptions: [
        'Exhibition opening in Kreuzberg. The room was full of people who see themselves in the work.',
        'Art therapy session with unaccompanied minors. The images they make break and rebuild me.',
        'Residency week 6 — the piece is becoming what it needs to be.',
        'Translating Farsi poetry into visual language. Some things don\'t need words.',
        'Lecture on art therapy and community healing at Goldsmiths. Students who will do good work.',
      ],
      source: 'og_tags',
    },
  },
  {
    name: 'Theo Williams',
    linkedinUrl: 'https://www.linkedin.com/in/theo-williams-demo/',
    instagramUrl: 'https://www.instagram.com/theo.plays.demo/',
    avatarSeed: 'theo',
    linkedinData: {
      name: 'Theo Williams',
      headline: 'Game Designer & Narrative Director | Naughty Dog | BAFTA Nominee',
      about: 'Narrative director at Naughty Dog. BAFTA-nominated for The Last of Us: Part III (narrative direction). Believe games are the most empathetic medium humans have invented. Teaching game narrative at USC.',
      skills: ['Game Design', 'Narrative Design', 'Screenwriting', 'Team Leadership', 'Teaching', 'Unreal Engine'],
      source: 'og_tags',
    },
    instagramData: {
      username: 'theo.plays.demo',
      profileUrl: 'https://www.instagram.com/theo.plays.demo/',
      displayName: 'Theo Williams',
      bio: '🎮 Narrative Director @NaughtyDog | BAFTA nominated | Games are empathy machines | USC teacher | 🎬 Film nerd | LA #gamedesign #narrativedesign #bafta',
      hashtags: ['#gamedesign', '#narrativedesign', '#bafta', '#gaming', '#losangeles'],
      recentCaptions: [
        'Shipped. 4 years of work. The credits rolled and I cried at my own game.',
        'Guest lecture at USC — 80 students who are about to change what games can be.',
        'Saturday cinema: rewatched "Yi Yi" for the fifth time. Still the greatest.',
        'Design workshop on non-linear narrative. The students kept breaking the framework in the best way.',
        'Playing through "Disco Elysium" for research. Call it research. It\'s research.',
      ],
      source: 'og_tags',
    },
  },
  {
    name: 'Simone Laurent',
    linkedinUrl: 'https://www.linkedin.com/in/simone-laurent-demo/',
    instagramUrl: 'https://www.instagram.com/simone.grows.demo/',
    avatarSeed: 'simone',
    linkedinData: {
      name: 'Simone Laurent',
      headline: 'Urban Farmer & Food Systems Consultant | Lyon → Detroit | Feeding Cities Differently',
      about: 'Building urban food systems that are equitable and regenerative. Converted 3 acres of Detroit vacant lots into community farms. Training formerly incarcerated individuals in sustainable agriculture. Lyon trained chef turned farmer.',
      skills: ['Urban Agriculture', 'Food Systems', 'Community Development', 'Permaculture', 'Social Enterprise'],
      source: 'og_tags',
    },
    instagramData: {
      username: 'simone.grows.demo',
      profileUrl: 'https://www.instagram.com/simone.grows.demo/',
      displayName: 'Simone Laurent',
      bio: '🌱 Urban farmer | Food justice | Detroit | Ex-chef, now feeding the city differently | Permaculture 🌿 | Lyon-trained #urbanfarming #foodjustice #detroit #permaculture',
      hashtags: ['#urbanfarming', '#foodjustice', '#detroit', '#permaculture', '#regenerativeagriculture'],
      recentCaptions: [
        'First harvest from the winter greenhouse. Kale in January in Michigan. We win.',
        'Reentry program: 12 graduates who now have jobs in food systems. This is the work.',
        'Lyon for a week — cooking family recipes, remembering why food matters.',
        'Urban agriculture coalition meeting. The city is finally listening.',
        'Soil health data from year 3 of our plot. The transformation is measurable.',
      ],
      source: 'og_tags',
    },
  },
  {
    name: 'Andre Baptiste',
    linkedinUrl: 'https://www.linkedin.com/in/andre-baptiste-demo/',
    instagramUrl: 'https://www.instagram.com/andre.composes.demo/',
    avatarSeed: 'andre',
    linkedinData: {
      name: 'Andre Baptiste',
      headline: 'Classical Composer & Conductor | Berlin Philharmonic Guest Conductor | Juilliard Faculty',
      about: 'Composer and conductor. Guest conductor with Berlin Philharmonic, Vienna Symphony, and New York Philharmonic. Work premiered at Carnegie Hall. Teaching composition at Juilliard. Haitian-American, writing music from the diaspora.',
      skills: ['Composition', 'Conducting', 'Music Theory', 'Orchestration', 'Teaching', 'Performance'],
      source: 'og_tags',
    },
    instagramData: {
      username: 'andre.composes.demo',
      profileUrl: 'https://www.instagram.com/andre.composes.demo/',
      displayName: 'Andre Baptiste',
      bio: '🎼 Composer + Conductor | @Juilliard faculty | Berlin Phil guest | Carnegie Hall | Haitian-American music | NYC #classical #composition #conducting #juilliard',
      hashtags: ['#classical', '#composition', '#conducting', '#juilliard', '#carnegiehal'],
      recentCaptions: [
        'World premiere of my Third Symphony. The orchestra was extraordinary. I wept in the wings.',
        'Teaching composition seminar: how do you write music that lasts? We don\'t know. We try.',
        'Berlin Philharmonic rehearsal. They make you a better conductor by being better than you.',
        'Writing at 3am — the music comes when it comes.',
        'Haiti trip for research. The Vodou ceremony rhythms I documented will appear in the Fourth Symphony.',
      ],
      source: 'og_tags',
    },
  },
]

export function getSyntheticPerson(index: number): SyntheticPerson {
  return SYNTHETIC_PEOPLE[index % SYNTHETIC_PEOPLE.length]
}
